### ISSUE TITLE
Make Public/Private Folders More Configurable

### ISSUE THREAD

**Issue by SingleShot** [rubyatscale/packwerk-extensions#25]
Hi. I find the single public folder configuration to be limiting and it sort of encourages mixing different concerns together. To avoid this I would like to be able to specify more than one public pattern. Imagine I have a `models` folder and a `services` folder, and each might have some things I want public and some I want private.

Rather than moving the public items into a common folder, and then fighting the loader if I want subfolders, I could instead just list a couple patterns in the package config. Maybe something like this:
```
public:
  includes:
    - app/models/*.rb
    - app/services/**/*.rb
  excludes:
    - app/models/AdminUser.rb
    - app/services/helpers
```

This lets me keep the different concerns like models/services still organized into their own folders, while still declaring my public interface, and also preserving the standard Rails folder structure within the pack.

Thanks for considering.
